jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

logging:
  level:
    org:
      mongodb: warn
oms:
  accurate:
    select:
      server:
        percentage: 50
  alarm:
    ding:
      agent-id: 847044348
      app-key: dingauqwkvxxnqskknfv
      app-secret: XWrEPdAZMPgJeFtHuL0LH73LRj-74umF2_0BFcoXMfvnX0pCQvt0rpb1JOJU_HLl
  container:
    retention:
      local: 1
      remote: -1
  env: @pom.artifactId@
  instance:
    metadata:
      cache:
        size: 1024
  instanceinfo:
    retention: 1
  mongodb:
    enable: false
  akka:
    port: 10086
  http:
    port: 10010
  table-prefix: ''
  transporter:
    active:
      protocols: AKKA,HTTP
    main:
      protocol: HTTP

server:
  port: 7700
spring:
  data:
    mongodb:
      uri: mongodb+srv://zqq:No1Bug2Please3!@cluster0.wie54.gcp.mongodb.net/powerjob_daily?retryWrites=true&w=majority
  datasource:
    core:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://@MYSQL-HOST@:@MYSQL-PORT@/@MYSQL-DB-POWER-JOB@?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      maximum-pool-size: 20
      minimum-idle: 5
      password: @MYSQL-PASSWORD@
      username: @MYSQL-USERNAME@
  mail:
    host: smtp.163.com
    username: zqq@163.com
    password: GOFZPNARMVKCGONV
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  jpa:
    open-in-view: false
  main:
    banner-mode: log
  profiles:
    active: daily
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 209715200
      max-request-size: 209715200
